### ISSUE TITLE
컬렉션 폴리싱 - UI 폴리싱 대응

### ISSUE THREAD

**Issue by tyrosine1153** [planetarium/NineChronicles#4335]
상위 이슈 : https://github.com/planetarium/NineChronicles/issues/4329

- https://github.com/planetarium/NineChronicles/issues/4325 이슈에서 나오는 개발 요청사항에 대응합니다.

## Todo
- [x] 준비 화면에 도감 이펙트 버튼 적용
- [x] 로딩 중일 때 완료된 목록은 비활성 버튼이 아닌 그대로.
- [ ] #4520
- [x] #4481
- [x] 결과 화면 Press to continue 텍스트 수정
- [x] 결과 화면 애니메이션 수정
- [x] 재료 등록 시 ItemView에 애니메이션 적용

**Comment by tyrosine1153** [comment]
- [ ] 준비 화면에 도감 이펙트 버튼 적용
- [ ] 로딩 중일 때 완료된 목록은 비활성 버튼이 아닌 그대로.
- [ ] Collection Show 시점 scale 애니메이션 적용
- [ ] 재료 상세 팝업에서 필요, 보유수량 텍스트 수정
- [ ] 결과 화면 Press to continue 텍스트 수정
- [ ] 결과 화면 애니메이션 수정
- [ ] 재료 등록 시 ItemView에 애니메이션 적용

**Comment by tyrosine1153** [comment]
- [ ] Collection Show 시점 scale 애니메이션 적용
- [ ] 재료 상세 팝업에서 필요, 보유수량 텍스트 수정

위의 두 작업은 기존 pr과 충돌 가능성이 있어 다른 pr로 적용 예정

**Comment by tyrosine1153** [comment]
#4520 제외 모두 160.0.0에 포함되었습니다. #4520은 이후 170.0.0에 작업해 포함할 예정으로 이 이슈는 Close합니다.
