### ISSUE TITLE
헤머 클라이언트 수정

### ISSUE THREAD

**Issue by tyrosine1153** [planetarium/NineChronicles#5234]
### Todo

- [x] AddHammerPopup UI 프리펩 추가된 것 대응
- [x] Enhancement (강화 화면) 강화 인벤토리에 망치 추가
  - [x] 망치 사용 구현
- [x] 액션 연결

**Comment by tyrosine1153** [comment]
기능 수정 중 코드 정리의 용량이 너무 많아 기존에 있던 enhancement 리펙토링 부분만 커밋을 분리해 올립니다. 
- #5412
